CREATE TABLE IF NOT EXISTS finances.customer_auth_identities(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),entity_id bigint NOT NULL REFERENCES finances.entities(id),business_unit_id bigint NOT NULL REFERENCES human_resource.business_units(id),provider varchar(20) NOT NULL CHECK(provider IN('phone','google','apple')),provider_subject varchar(255) NOT NULL,phone_e164 varchar(20),email_normalized varchar(320),email_verified boolean NOT NULL DEFAULT false,phone_verified boolean NOT NULL DEFAULT false,display_name varchar(255),avatar_url text,last_login_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(business_unit_id,provider,provider_subject));
CREATE INDEX IF NOT EXISTS idx_customer_auth_entity ON finances.customer_auth_identities(entity_id,business_unit_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_customer_auth_phone ON finances.customer_auth_identities(business_unit_id,phone_e164) WHERE provider='phone' AND phone_verified;
CREATE TABLE IF NOT EXISTS finances.customer_otp_challenges(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),business_unit_id bigint NOT NULL REFERENCES human_resource.business_units(id),purpose varchar(24) NOT NULL DEFAULT 'login',phone_e164 varchar(20) NOT NULL,code_hash char(64) NOT NULL,attempts smallint NOT NULL DEFAULT 0,max_attempts smallint NOT NULL DEFAULT 5,expires_at timestamptz NOT NULL,consumed_at timestamptz,requested_ip inet,user_agent text,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_customer_otp_active ON finances.customer_otp_challenges(business_unit_id,phone_e164,created_at DESC) WHERE consumed_at IS NULL;
CREATE TABLE IF NOT EXISTS finances.customer_mobile_sessions(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),identity_id uuid NOT NULL REFERENCES finances.customer_auth_identities(id) ON DELETE CASCADE,entity_id bigint NOT NULL REFERENCES finances.entities(id),business_unit_id bigint NOT NULL REFERENCES human_resource.business_units(id),refresh_token_hash char(64) NOT NULL UNIQUE,token_family uuid NOT NULL DEFAULT gen_random_uuid(),device_id varchar(255),platform varchar(20),app_version varchar(40),last_ip inet,last_seen_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL,revoked_at timestamptz,revoke_reason varchar(80),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_customer_sessions_active ON finances.customer_mobile_sessions(identity_id,expires_at) WHERE revoked_at IS NULL;
CREATE TABLE IF NOT EXISTS restaurant.mobile_order_requests(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),business_unit_id bigint NOT NULL,entity_id bigint NOT NULL,idempotency_key varchar(100) NOT NULL,request_hash char(64) NOT NULL,status varchar(20) NOT NULL CHECK(status IN('processing','completed','failed')),account_id bigint,response_json jsonb,error_code varchar(80),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(business_unit_id,entity_id,idempotency_key));
